services:
  task_manager:
    build: 
      context: .
      dockerfile: DockerfileGoWithRedisProject
    image: task_manager:0.1
    ports:
      - 8082:8082
    environment:
      - REDIS_HOST=redis:6379
    healthcheck: # Проверяем работоспособность
      test: ["CMD", "curl", "-f", "http://localhost:8082/ping"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on: # Ждём redis
      - redis
  redis:
    image: redis
    ports:
      - 6380:6379
  redis_populate:
    image: redis
    depends_on:
      - redis
    env_file:
      - ./env.redis_populate
