services:
  task_manager:
    build: 
      context: .
      dockerfile: DockerfileGoWithRedisProject
      labels:
        - com.packtpub.compose.app=task_manager
    image: task_manager:0.1
    ports:
      - 8082:8082
    environment:
      - REDIS_HOST=redis:6379
    healthcheck: # Проверяем работоспособность
      test: ["CMD", "curl", "-f", "http://localhost:8082/ping"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on: # Ждём redis
      - redis
  redis:
    image: redis
    ports:
      - 6380:6379
  redis_populate:
    image: redis
    command: bash -c "chmod +x /redis_populate.sh && /redis_populate.sh /redis_populate.txt"
    depends_on:
      - redis
    env_file:
      - ./env.redis_populate
    volumes:
      - ./redis_populate.txt:/redis_populate.txt
      - ./redis_populate.sh:/redis_populate.sh
