services:
  task_manager:
    build:
      context: .
      dockerfile: DockerfileGoWithRedisProject
      labels:
        - com.packtpub.compose.app=task_manager
    image: task_manager:0.1
    ports:
      - 8082:8082
    environment:
      - REDIS_HOST=redis:6379
    healthcheck: # Проверяем работоспособность
      test: ["CMD", "curl", "-f", "http://localhost:8082/ping"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on: # Ждём redis
      - redis
  redis:
    image: redis
    ports:
      - 6380:6379
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
  redis_populate: # Заполнение бдшки базовыми данными
    image: redis
    command: bash -c "chmod +x /redis_populate.sh && /redis_populate.sh /redis_populate.txt"
    depends_on:
      - redis
    env_file:
      - ./env.redis_populate
    volumes:
      - ./redis_populate.txt:/redis_populate.txt
      - ./redis_populate.sh:/redis_populate.sh
  redis_backup:
    image: bash
    entrypoint: ["/snapshot-backup.sh"]
    depends_on: # Запуск после redis
      - redis
    environment:
      - BACKUP_PERIOD=10
    volumes:
      - ./snapshot-backup.sh:/snapshot-backup.sh
      - redis-data:/data:ro # ro - read only
      - backup:/backup
volumes: # Общие хранилища
  redis-data:
    external: true
  backup: # Тот для бэкапов

